# Generated by Django 4.1.1 on 2022-09-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_registration_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="pw",
            new_name="password",
        ),
    ]
